## dev环境使用是配置
server:
  port: 8081
  context-path: /chao


spring:
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5
    cache: false
  ## freemarker
  freemarker:
    charset: UTF-8
    content-type: text/html
    cache: false
    suffix: .html
  ##数据sql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo_docker
    username: root
    password: 123456

#  可以在application 上面加注解
#  效果相同
#  @MapperScan(value = "demo.spring.boot.demospringboot.mybatis.dao")
mybatis:
  mapper-locations: classpath:mybatis/dao/*Mapper.xml
  config-location: classpath:mybatis/config/mybatis-config.xml




url:
  security:
    ## 拦截需要验证的url,数组的形式
    ## authenticated: /private/**,/framework/**
    authenticated: /private/**







